name: Deploy to Staging

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: golang:1.13
    steps:
      - uses: actions/checkout@v2
      - name: Bootstrap
        run: |
          apt-get update
          apt-get install -y zip awscli
      - name: Build and zip
        run: |
          COMMIT=$(shell git rev-parse HEAD)
          CGO_ENABLED=0 GOOS=linux go build -o main -X 'github.com/bitmaelum/key-resolver-go/internal.GitCommit=${COMMIT}' cmd/lambda/main.go
          zip -r ./function.zip main
      - name: deploy zip to lambda
        run: |
          aws lambda update-function-code --function-name key-resolve-staging --zip-file fileb://function.zip --publish
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
