name: Deploy Redoc openAPI documentation

on:
  push:
    branches: [ master, redoc ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate redoc file
        run: |
          npm install redoc-cli
          ./node_modules/.bin/redoc-cli bundle openapi/openapi.yaml
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: deploy file
        run: |
          scp redoc-static.html ${{ secrets.OPENAPI_DEPLOY_PATH }}/index.html
