name: Deploy REedoc

on:
  push:
    branches: [ master, redoc ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate redoc file
        run: |
          npm install redoc-cli
          ./node_modules/.bin/redoc-cli bundle openapi/openapi.yaml
          mkdir deploy
          cp redoc-static.html deploy/index.html
      - name: deploy file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "deploy/index.html"
          target: "/home/bitmaelum/domains/api-docs.bitmaelum.com/public_html"
